FROM python:3.9-slim

WORKDIR /mlflow

# Installer MLflow
RUN pip install --no-cache-dir mlflow==2.9.2

# Exposer le port
EXPOSE 5000

# Lancer MLflow UI
CMD ["mlflow", "ui", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:///mlflow.db"]

